name: Add labels

on:
  issue_comment:
    types: [created, edited]
env:
  APP_NAME: nextjs-start

jobs:
  get-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Echo comment body
        run: |
          echo "$GITHUB_CONTEXT"
          echo "comment=${{ github.event.comment.body }}" >> $GITHUB_OUTPUT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: get comment label
        id: get_comment_label
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run:
          python .github/utils/parse_comment.py

      - name: Add release label
        uses: actions/github-script@v6
        with:
          script: |
            echo "${{ steps.get_comment_label.outputs.COMMENT_JSON }}"
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["deploy-nextjs-start"]
            })
