name: Add labels

on:
  issue_comment:
    types: [created, edited]
env:
  APP_NAME: nextjs-start

jobs:
  get-comment:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/add-labels:deploy')
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2.3.4
      - name: Echo GITHUB_CONTEXT
        run: |
          echo "$GITHUB_CONTEXT"
          echo "comment=${{ github.event.comment.body }}" >> $GITHUB_OUTPUT
          echo  "${{github.workspace}}"
          ls -a "${{github.workspace}}"
          ls -a "${{github.workspace}}/.github"
          ls -a "${{github.workspace}}/.github/utils"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      # - name: Parse comment by github script
      #   uses: actions/github-script@v6
      #   id: parse-comment
      #   with:
      #     script: |
      #       const str = "${{ github.event.comment.body }}".toString();
      #       const arr = str.split(':')[1].split(',');
      #       console.log(arr);
      #       github.rest.issues.addLabels({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         labels: arr
      #       })
      - name: Parse comment by github script
        uses: actions/github-script@v6
        id: parse-comment
        with:
          script: |
             const { default: CreateDeployLabels } = await import('${{ github.workspace }}/.github/utils/add-labels.mjs');
             console.log('github', github);
             console.log('context', context);
             await CreateDeployLabels({github, context});
      - name: Create version comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          issue-number: ${{ github.event.issue.number}}
          body: |
            -----
            Congrats, add-labels successfully!
            commit-id: $GITHUB_SHA
            meganode-ui-PR: ${{ github.event.issue.html_url }}
          reactions: eyes, hooray, rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      # - uses: actions-ecosystem/action-regex-match@v2
      #   id: regex-match
      #   if: startsWith(${{ github.event.comment.body }}, 'add-labels:')
      #   with:
      #     text: ${{ github.event.comment.body }}
      #     regex: '([^:,]+)'

      # - uses: actions-ecosystem/action-add-labels@v1
      #   if: ${{ steps.regex-match.outputs.match != '' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     labels: |
      #       ${{ steps.regex-match.outputs.group1 }}
      #       ${{ steps.regex-match.outputs.group2 }}
      #       ${{ steps.regex-match.outputs.group3 }}
      #       ${{ steps.regex-match.outputs.group4 }}
      #       ${{ steps.regex-match.outputs.group5 }}
      #       ${{ steps.regex-match.outputs.group6 }}
      #       ${{ steps.regex-match.outputs.group7 }}
      #       ${{ steps.regex-match.outputs.group8 }}
      #       ${{ steps.regex-match.outputs.group9 }}

      # - name: install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      # - name: get comment label
      #   id: get_comment_label
      #   env:
      #     COMMENT_BODY: ${{ github.event.comment.body }}
      #   run: |
      #     python .github/utils/parse_comment.py
      # - name: Add release label
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       echo "$LABEL"
      #       github.rest.issues.addLabels({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         labels: [ "nextjs-start" ]
      #       })
      #   env:
      #      LABEL: ${{ steps.get_comment_label.outputs.COMMENT_LABELS }}
      #     #  COMMENT_JSON: ${{ steps.get_comment_label.outputs.COMMENT_JSON }}