name: get other project

on:
  push:
    branches:
      - "get-other-project"
env:
  APP_NAME: nextjs-start

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit
        run: |
          CURRENT_HASH=$(git rev-parse HEAD)
          LAST_BUILD_HASH="51d9c8b7f078137f224b1d98ea04417437fa600e"
          echo "$LAST_BUILD_HASH"
          echo "$CURRENT_HASH"
          DIFF="$(git log --oneline > changelog.md)"
          echo "------------"
          echo "$(cat changelog.md)"
          echo "------------"
          echo "$(git log)"
          echo "$DIFF"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout previous commit
        uses: actions/checkout@v3
        with:
          repository: randomxiang/github-actions-demo
          ref: main
          path: github-action-demo
          token: ${{ secrets.GH_PAT }}
      - name: ls -a
        run: |
          ls -a
      - name: ls -a github-action-demo
        run: |
          ls -a .github
      - name: ls -a .github/utils
        run: |
          ls -a .github/utils
      - name: get online release tag
        id: get_production_commit
        run: |
          RELEASE_TAG=$(yq eval '.node-app.image.tag' github-action-demo/config/ui/values.yaml)
          echo "production_commit=${RELEASE_TAG}" >> $GITHUB_OUTPUT
      - name: show env
        run: |
          echo "${{steps.get_production_commit.outputs.production_commit}}"
      - name: commit 2
        run: |
          # get current commit hash
          CURRENT_HASH=$(git rev-parse HEAD)
          LAST_BUILD_HASH=${{steps.get_production_commit.outputs.production_commit}}
          # get last commit hash of last build dist
          DIFF=""
          # build and commit dist if diff
          # if last commit hash of last build dist was found, get logs of commits in btw for PR body
          if [ -z "$LAST_BUILD_HASH" ]
          then
                echo "Unable to find last commit by bot, skipping diff gen"
          else
                DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --pretty=format:%s )
                echo $DIFF
          fi
          # set env vars
          echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
          echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
          echo 'DIFF<<EOF' >> $GITHUB_ENV
          echo "${DIFF}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
    # const str = diff.split('\n').filter(m => !/^(Merge pull request|Merge branch)/.test(m)).join('\n');
    #     console.log('str', str);
      - name: parse-comment
        uses: actions/github-script@v6
        id: parse_commits
        with:
         script: |
           const diffMsgs = `${{env.DIFF}}`;
           console.log('diffMsgs', diffMsgs, typeof diffMsgs)
           const script = require("${{ github.workspace }}/.github/utils/parse-commit-msg.js");
           await script({diffMsgs, core});
      - name: echo parse_commits
        run: |
          DIFF_COMMITS="${{ steps.parse_commits.outputs.commits }}"
          echo 'DIFF_COMMITS<<EOF' >> $GITHUB_ENV
          echo "${DIFF_COMMITS}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo $DIFF_COMMITS > diff_commits
      - name: Echo github sha
        run: |
          echo "${GITHUB_SHA}"

      - name: Upload diff commits
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.pull_request.number }}_diff_commits
          path: diff_commits

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: checkout github action demo
        uses: actions/checkout@v3

      - name: test env
        run: |
          echo "${GITHUB_SHA}"
          echo '----------------'
          echo "${{ env.DIFF_COMMITS }}"

      - name: Upload diff commits
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.pull_request.number }}_diff_commits
          path: ./artifacts
      - name: Display structure of downloaded files
        run: |
          FILE_NAME=${{ github.event.pull_request.number }}_diff_commits
          echo $FILE_NAME
          DIFF_COMMITS=$(cat artifacts/$FILE_NAME)
          echo '------------------'
          echo $DIFF_COMMITS