name: Add labels

on:
  push:
    branches:
      - "get-other-project"
env:
  APP_NAME: nextjs-start

jobs:
  get-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit
        run: |
          CURRENT_HASH=$(git rev-parse HEAD)
          LAST_BUILD_HASH="51d9c8b7f078137f224b1d98ea04417437fa600e"
          echo "$LAST_BUILD_HASH"
          echo "$CURRENT_HASH"
          DIFF="$(git log --oneline > changelog.md)"
          echo "------------"
          echo "$(cat changelog.md)"
          echo "------------"
          echo "$(git log)"
          echo "$DIFF"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout previous commit
        uses: actions/checkout@v3
        with:
          repository: randomxiang/github-actions-demo
          ref: main
          token: ${{ secrets.GH_PAT }}
      - name: ls
        run: |
          ls
      - name: ls config
        run: |
          ls config
      - name: ls config/ui
        run: |
          ls config/ui
      - name: get online release tag
        id: get_production_commit
        run: |
          RELEASE_TAG=$(yq -r '.node-app.image.tag' config/ui/values.yaml)
          echo "production_commit=${RELEASE_TAG}" >> $GITHUB_OUTPUT
      - name: show env
        run: |
          echo "${{steps.get_production_commit.outputs.production_commit}}"
      - name: commit 2
        run: |
          # get current commit hash
          CURRENT_HASH=$(git rev-parse HEAD)
          # get last commit hash of last build dist
          LAST_BUILD_HASH="${{steps.get_production_commit.outputs.production_commit}}"
          DIFF=""
          # build and commit dist if diff
          # if last commit hash of last build dist was found, get logs of commits in btw for PR body
          if [ -z "$LAST_BUILD_HASH" ]
          then
                echo "Unable to find last commit by bot, skipping diff gen"
          else
                DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --pretty=oneline)
                echo $DIFF
          fi
          # set env vars
          echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
          echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
          echo 'DIFF<<EOF' >> $GITHUB_ENV
          echo "${DIFF}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV