name: test collection

on:
  push:
    branches:
      - "test"
jobs:
  test-ignore-error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      - name: Get Release Diff Commits
        id: get_diff_commits
        continue-on-error: true
        run: |
          CURRENT_HASH=$(git rev-parse HEAD)
          LAST_BUILD_HASH=646b7c4b76cca43fd868cf5fc9244577986b0000
          DIFF=""
          if [ -z "$LAST_BUILD_HASH" ]
          then
                echo "Unable to find last commit by bot, skipping diff gen"
          else
                DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --pretty=format:%s)
                echo $DIFF
          fi
          echo 'DIFF<<EOF' >> $GITHUB_ENV
          echo "${DIFF}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Prune Commit Msg
        run: |
            echo "1111"
      - name: Prune Commit Msg
        run: |
            echo "${{env.DIFF}}"
      - name: Prune Commit Msg
        id: prune_commit_msg
        uses: actions/github-script@v6
        with:
          script: |
            const diff_commits = `${{env.DIFF}}`
            const script = require("${{ github.workspace }}/.github/utils/parse-diff-commits.js");
            await script({diff_commits, core});
      - name: Generate Artifacts
        run: |
          mkdir temp
          echo "${{ steps.prune_commit_msg.outputs.commits }}" > temp/commit_changes
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "test_qa_artifacts"
          path: temp
          if-no-files-found: error