name: workflow_dispatch deploy the 'main' branch or a tag scheduler

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Release the project manually."
        required: true
        default: "web-ui"
        type: string
      env:
        description: "Choose the environment for deployment."
        required: true
        default: "testnet"
        type: string
      ref:
        description: "Specify the branch or a tag to deploy"
        required: true
        default: "main"
        type: string
jobs:
  pre-check:
    runs-on: ubuntu-latest
    if: ((github.event.inputs.project == 'web-ui') && ((github.event.inputs.env == 'testnet') || (github.event.inputs.env == 'mainnet')))
    outputs:
      codeowners: ${{ steps.codeowners.outputs.content }}
      is_valid_ref: ${{ steps.check_ref.outputs.is_valid_ref }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Read codeowners
      id: codeowners
      uses: juliangruber/read-file-action@v1
      with:
        path: .github/CODEOWNERS
    - name: Check if ref is a valid tag on main branch
      id: check_ref
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const ref = '${{ github.event.inputs.ref }}';
          let is_valid_ref = false;
          let ref_type = ''; # Can be 'branch' or 'tag'

          # Check if ref is main branch
          if (ref === 'main') {
            is_valid_ref = true;
            ref_type = 'branch';
          } else {
            # Check if ref is a tag
            const tags = await github.rest.git.listMatchingRefs({
              owner,
              repo,
              ref: `tags/${ref}`,
            });

            if (tags.data.length > 0) {
              # If it's a tag, check if the tag is on the main branch
              const commitsOnMain = await github.rest.repos.listCommits({
                owner,
                repo,
                sha: 'main',
                per_page: 100,
              });

              const tagCommitSha = tags.data[0].object.sha;
              is_valid_ref = commitsOnMain.data.some(commit => commit.sha === tagCommitSha);

              if (is_valid_ref) {
                ref_type = 'tag';
              }
            }
          }

          core.setOutput('is_valid_ref', is_valid_ref);
          core.setOutput('ref_type', ref_type);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-codeowners:
    runs-on: ubuntu-latest
    needs: [pre-check]
    if: (!contains(needs.pre-check.outputs.codeowners, github.event.comment.user.login))
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create Version Comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        comment-id: ${{ github.event.comment.id }}
        body: |
          ++++++
          Deployment request denied. Please ensure you have the necessary permissions by contacting the project code owners.
        reactions: rocket
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  web-ui-prod-deploy:
    runs-on: ubuntu-latest
    needs: [pre-check]
    if: ((needs.pre-check.outputs.is_valid_ref == 'valid') && (inputs.project == 'web-ui') && (inputs.env == 'mainnet'))
    name: Mock Deploy
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4